### ISSUE TITLE
Tests local server not responding, Timeout awaiting 'request'

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1145] opened 2021-06-16 08:44 UTC
We've seen this happening a couple times already. This means that the server did not get started in time. We can always increase this value :shrug: 
```
http://localhost:3000 timed out on retry 7 of 5, elapsed 154107ms, limit 150000ms
Error: Timeout awaiting 'request' for 30000ms
```
example: https://github.com/ChainSafe/files-ui/pull/1144/checks?check_run_id=2832350306

![image](https://user-images.githubusercontent.com/33178835/122186248-2799c980-ce8e-11eb-9dbb-7c2552854bb3.png)

**Comment by asnaith** [comment] 2021-06-18 17:07
Dupe of #1131?

**Comment by Tbaut** [comment] 2021-06-21 09:36
Nope this is different, in the one you mention (that I already opened an issue for), the server launches, some tests pass, then comes the test with the viewport change, it lags and fails.
In this issue, the server is not launched within 2min, and all tests fail. This happens very rarely.. and I don't think there's much we can do unfortunately except letting even more time.. but honestly 2min is already quite a lot.

**Comment by asnaith** [comment] 2021-06-21 23:11
@Tbaut Ok. Yeah 2 minutes is already quite substantial. 

Let's see if switching to chrome instead of electron also improves this issue.

**Comment by Tbaut** [comment] 2021-08-24 16:35
Here's the only instance of the same error that I found on the internetz https://github.com/cypress-io/github-action/issues/286

I'll first start by adding a debug and check the job and try to see something out of that.
Then I'll try to increase the timeout, and if that doesn't help I'll play with the `start-server-and-test` as instructed in https://github.com/cypress-io/github-action/issues/286#issuecomment-784423702

**Comment by Tbaut** [comment] 2021-08-24 22:29
I've a hard time making it fail with the debug :see_no_evil: 
But I still get some error that may be interesting to dig deeper into

```
Run cypress-io/github-action@v2
/usr/bin/docker exec  a86b2571558f5be3ad515cf9a9dfdc5061ea62e5eeca835e55832943ab247d95 sh -c "cat /etc/*release | grep ^ID"
2021-08-24T22:26:17.483Z @cypress/github-action working directory /__w/ui-monorepo/ui-monorepo
2021-08-24T22:26:17.485Z @cypress/github-action using custom Cypress cache folder "/github/home/.cache/Cypress"
2021-08-24T22:26:17.485Z @cypress/github-action trying to restore cached NPM modules
2021-08-24T22:26:17.490Z @cypress/github-action Hash from file /__w/ui-monorepo/ui-monorepo/yarn.lock is 67a5f8e96b4774db89067f7d65b8ac8675dc6503a3c76f9fcbfd757a672b8bb9623d1177f5fd00742bf860c39440d9e9169c20d48649612900e9530668acf826
2021-08-24T22:26:17.493Z @cypress/github-action trying to restore cached Cypress binary
2021-08-24T22:26:17.496Z @cypress/github-action Hash from file /__w/ui-monorepo/ui-monorepo/yarn.lock is 67a5f8e96b4774db89067f7d65b8ac8675dc6503a3c76f9fcbfd757a672b8bb9623d1177f5fd00742bf860c39440d9e9169c20d48649612900e9530668acf826
Received 45 of 45 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (45 B)
/bin/tar -z -xf /__w/_temp/88cb1d1a-b379-4883-af03-54ee958a8ee9/cache.tgz -P -C /__w/ui-monorepo/ui-monorepo
Cache restored successfully
Received 184148404 of 188342708 (97.8%), 175.6 MBs/sec
Received 188342708 of 188342708 (100.0%), 157.7 MBs/sec
Cache Size: ~180 MB (188342708 B)
/bin/tar -z -xf /__w/_temp/86d7337e-5909-45c2-926c-7fa9c4e5d1e8/cache.tgz -P -C /__w/ui-monorepo/ui-monorepo
Cache restored successfully
2021-08-24T22:26:24.842Z @cypress/github-action npm cache hit yarn-linux-x64-67a5f8e96b4774db89067f7d65b8ac8675dc6503a3c76f9fcbfd757a672b8bb9623d1177f5fd00742bf860c39440d9e9169c20d48649612900e9530668acf826
2021-08-24T22:26:24.842Z @cypress/github-action cypress cache hit cypress-linux-x64-67a5f8e96b4774db89067f7d65b8ac8675dc6503a3c76f9fcbfd757a672b8bb9623d1177f5fd00742bf860c39440d9e9169c20d48649612900e9530668acf826
2021-08-24T22:26:24.844Z @cypress/github-action installing NPM dependencies using Yarn
2021-08-24T22:26:24.845Z @cypress/github-action yarn at "/usr/local/bin/yarn"
/usr/local/bin/yarn --frozen-lockfile
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn build:common
yarn run v1.22.10
$ yarn build:theme && yarn build:components
$ yarn wsrun -t -p @chainsafe/common-theme -c build
$ /__w/ui-monorepo/ui-monorepo/node_modules/.bin/wsrun -t -p @chainsafe/common-theme -c build
@chainsafe/common-theme
 | $ rollup -c
 | 
 | src/index.ts → dist/...
 | created dist/ in 4s
$ yarn wsrun -t -p @chainsafe/common-components -c build
$ /__w/ui-monorepo/ui-monorepo/node_modules/.bin/wsrun -t -p @chainsafe/common-components -c build
@chainsafe/common-components
 | $ rollup -c
 | 
 | ./src/index.ts → dist/...
 | created dist/ in 21s
Done in 28.31s.
Done in 30.14s.
2021-08-24T22:26:55.134Z @cypress/github-action install has finished
2021-08-24T22:26:55.135Z @cypress/github-action Cypress versions in the cache folder /github/home/.cache/Cypress
/usr/local/bin/npx cypress cache list
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 8.3.0   │ a few seconds ago │
└─────────┴───────────────────┘
2021-08-24T22:26:55.465Z @cypress/github-action no need to verify Cypress binary or save caches
2021-08-24T22:26:55.465Z @cypress/github-action Separated 1 start commands yarn start:files-ui
2021-08-24T22:26:55.466Z @cypress/github-action parsed command: yarn start:files-ui
start server "yarn start:files-ui command "yarn start:files-ui"
current working directory "/__w/ui-monorepo/ui-monorepo"
2021-08-24T22:26:55.467Z @cypress/github-action Waiting for urls http://localhost:3000
waiting on "http://localhost:3000" with timeout of 120 seconds
2021-08-24T22:26:55.468Z @cypress/github-action Waiting for url http://localhost:3000
2021-08-24T22:26:55.468Z @cypress/github-action total ping timeout 150000
2021-08-24T22:26:55.468Z @cypress/github-action individual ping timeout 30000ms
2021-08-24T22:26:55.469Z @cypress/github-action retries limit 5
2021-08-24T22:26:55.483Z @cypress/github-action got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1629844015474,"socket":1629844015475,"lookup":1629844015476,"error":1629844015476,"phases":{"wait":1,"dns":1,"total":2}}}
2021-08-24T22:26:55.483Z @cypress/github-action 14ms undefined undefined ECONNREFUSED attempt 1
2021-08-24T22:26:55.484Z @cypress/github-action found command "/usr/local/bin/yarn"
2021-08-24T22:26:55.484Z @cypress/github-action with arguments start:files-ui
2021-08-24T22:26:55.484Z @cypress/github-action running "/usr/local/bin/yarn" start:files-ui in /__w/ui-monorepo/ui-monorepo
2021-08-24T22:26:55.484Z @cypress/github-action waiting for the command to finish? false
/usr/local/bin/yarn start:files-ui
yarn run v1.22.10
$ yarn wsrun -p files-ui -c start
$ /__w/ui-monorepo/ui-monorepo/node_modules/.bin/wsrun -p files-ui -c start
files-ui
 | $ yarn compile && craco --max_old_space_size=4096 start
 | $ lingui compile
2021-08-24T22:26:56.487Z @cypress/github-action got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1629844016485,"socket":1629844016486,"lookup":1629844016486,"error":1629844016486,"phases":{"wait":1,"dns":0,"total":1}}}
2021-08-24T22:26:56.487Z @cypress/github-action 1018ms undefined undefined ECONNREFUSED attempt 2
 | Compiling message catalogs…
 | Done!
2021-08-24T22:26:57.490Z @cypress/github-action got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1629844017489,"socket":1629844017489,"lookup":1629844017489,"error":1629844017489,"phases":{"wait":0,"dns":0,"total":0}}}
2021-08-24T22:26:57.490Z @cypress/github-action 2021ms undefined undefined ECONNREFUSED attempt 3
2021-08-24T22:26:58.493Z @cypress/github-action got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1629844018492,"socket":1629844018492,"lookup":1629844018492,"error":1629844018492,"phases":{"wait":0,"dns":0,"total":0}}}
2021-08-24T22:26:58.493Z @cypress/github-action 3024ms undefined undefined ECONNREFUSED attempt 4
 | ℹ ｢wds｣: Project is running at http://172.18.0.2/
 | ℹ ｢wds｣: webpack output is served from 
 | ℹ ｢wds｣: Content not from webpack is served from /__w/ui-monorepo/ui-monorepo/packages/files-ui/public
 | ℹ ｢wds｣: 404s will fallback to /
 | Starting the development server...
 | 
2021-08-24T22:27:29.496Z @cypress/github-action got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1629844019494,"socket":1629844019494,"lookup":1629844019494,"connect":1629844019494,"upload":1629844019494,"error":1629844049496,"phases":{"wait":0,"dns":0,"tcp":0,"request":0,"total":30002}},"event":"request"}
2021-08-24T22:27:29.497Z @cypress/github-action 34028ms undefined undefined ETIMEDOUT attempt 5
 | Compiled successfully!
 | 
 | You can now view files-ui in the browser.
 | 
 |   Local:            http://localhost:3000
 |   On Your Network:  http://172.18.0.2:3000
 | 
 | Note that the development build is not optimized.
 | To create a production build, use npm run build.
 | 
2021-08-24T22:28:12.269Z @cypress/github-action pinging http://localhost:3000 has finished ok after 76800ms
```

**Comment by asnaith** [comment] 2021-08-25 05:09
Ah, well at least this totally makes sense with regards to the unreliability! 

You can see that in the log it's trying to perform the actions before the server is up. I was thinking the webserver was just hanging in ci and didn't think it was specifically within the realm of cypress. Seems like we've been getting into a race every time and lucky on the occasions the compilation and server startup is complete before cypress attempts to do it's a thing. I'm really surprised that Cypress doesn't have the functionality to check the server before attempting to run commands!

Knowing what we know now I think we should skip trying to increase the timeout and use the `wait-on` or  `start-server-and-test` modules. Better to be absolutely certain the server is available before letting cypress off the leash.

**Closed as completed** 2021-08-25 13:57 UTC
Labels: Testing, Issue: Bug 🐛
