### ISSUE TITLE
ChainSafe Storage: User can pin the same file multiple times

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1212] opened 2021-06-30 19:28 UTC
**Description**
It is possible for the user to repeatedly pin the same file. 

**To Reproduce**
1. Login to ChainSafe storage 
2. Navigate to the Cids page
3. Click on the Pin CID button
4. Paste a CID into the input box
5. Click Pin
6. Repeat steps 2 -5 with the same CID

**Expected behavior**
I don't think there's a use case for this behaviour so perhaps it would be better to inform the user that they have already pinned that CID?

**Screenshots**
<img width="1368" alt="Screen Shot 2021-06-30 at 11 57 15 AM" src="https://user-images.githubusercontent.com/3982665/124019996-97d04100-d99e-11eb-923c-af244aa1c113.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome version 91.0.4472.114, Firefox version 89.0.2

**Comment by Tbaut** [comment] 2021-07-01 08:34
Although it doesn't make too much sense, I don't think this is an issue, what's your opinion @kalambet  @FSM1?

**Comment by kalambet** [comment] 2021-07-01 08:41
That is how it intended to work, technically we are displaying not **pins** but **pin objects** that got built from **pin requests**, so you are operating with set of object built from requests that can be satisfied or not. So if you asked service to pin your cid multiple times we are going to display all your attmepts.

https://ipfs.github.io/pinning-services-api-spec/#section/The-pin-lifecycle

**Comment by Tbaut** [comment] 2021-07-01 09:48
Thanks @kalambet , what happens in the following scenario:
- user pins a CID 2 times
- user unpins this CID 1 time (for 1 of the previous pinObject)

The UI will still show the CID pin once, and it will effectively still be pinned right?

**Comment by kalambet** [comment] 2021-07-01 09:56
No, `cid` will be gone, those are previous requests to pin that were satisfied, but any request to unpin - removes file from cache. You can't pin anything more than one time in one pinning service, since it is a content based scheme.

**Comment by Tbaut** [comment] 2021-07-01 10:04
hmm then this is weird, this means that the pin status is not reflecting the actual state of things. Example, I have pinned the same cid twice, we have 2 pinObjects, both in "pinned" status.
![image](https://user-images.githubusercontent.com/33178835/124106077-2bb81080-da64-11eb-9a03-d729a6fa8fe2.png)

I unpin the older one, the remaining `pinObject` still shows up as "pinned", although you tell me that the reality is that it's not pinned any more?
![image](https://user-images.githubusercontent.com/33178835/124106455-82bde580-da64-11eb-9809-4af36afeb90b.png)

**Comment by FSM1** [comment] 2021-07-01 10:30
> Although it doesn't make too much sense, I don't think this is an issue, what's your opinion @kalambet @FSM1?

I think the behavior here really depends on the billing/usage side of things. 
If a user pins the same 10KiB CID twice, does this count as 20KiB usage even though we are only storing 10KiB on the system? If this is the case, then I think it would at least make sense to "warn" the user that they are pinning content that they have already pinned.

> No, `cid` will be gone, those are previous requests to pin that were satisfied, but any request to unpin - removes file from cache. You can't pin anything more than one time in one pinning service, since it is a content based scheme.

If this is the case, and the second item that is displayed is now no longer pinned, then we should definitely not allow the user to pin the same content twice, to prevent showing a pin object with a pinned status, that is no longer actually pinned.

**Comment by FSM1** [comment] 2021-07-01 10:37
@kalambet another scenario I wanted to run past you:
1. User A pins CID `abc`
2. User B also pins CID `abc`
3. User A unpins CID `abc`

Will CID `abc` still be pinned?

**Comment by kalambet** [comment] 2021-07-01 10:40
It's rather pin requests you showing, the whole concept is build as a "pin request/pin status" centric one.
Since it's the "pin status" you are really care about and not the object you are pinning - then you can even replace cid inside this "pin status": https://ipfs.github.io/pinning-services-api-spec/#section/The-pin-lifecycle/Replacing-an-existing-pin-object

The whole idea that you are holding a "pin status" of a pice of the data you need, the data itself might change, hence `cid` will change but "pin status" will reflect the current state.

So yeah, you probably right, we need to count how many times one user asked to pin one `cid` and not remove it unless all "pin status" is gone. Will create an issue.

**Comment by kalambet** [comment] 2021-07-01 10:40
> @kalambet another scenario I wanted to run past you:
> 
> 1. User A pins CID `abc`
> 2. User B also pins CID `abc`
> 3. User A unpins CID `abc`
> 
> Will CID `abc` still be pinned?

Yes, we are counting cross-user references.

**Comment by Tbaut** [comment] 2021-07-01 11:11
> The whole idea that you are holding a "pin status" of a pice of the data you need, the data itself might change, hence cid will change but "pin status" will reflect the current state.

This is I think where there's a problem. If you tell me the  "pin status will reflect the current state", what you told me before is not consistent with what I see, e.g when you unpin a CID that is present in 2 `pinObject`, then you'll unpin the CID. As my screenshot suggests, the pinning status of the remaining `pinObject` is showing "pinned", although according to what you say it should show something like "unpineed/not pinned" or something along this line, because the corresponding CID has been unpinned. So the status is not up to date.

edit: maybe as you say the solution is to prevent pinning twice the same CID (per user ofc). We'll reflect this error in the UI and the problem is solved.

**Comment by kalambet** [comment] 2021-07-01 12:00
> when you unpin a CID that is present in 2 pinObject, then you'll unpin the CID. As my screenshot suggests, the pinning status of the remaining pinObject is showing "pinned", although according to what you say it should show something like "unpineed/not pinned" or something along this line, because the corresponding CID has been unpinned. 

Current API behaviour is wrong, that is why I wrote "we need to count how many times one user asked to pin one cid and not remove it unless all "pin status" is gone. Will create an issue."
What I mean by that, is that we need to make sure that each pint request counts. You asked to pin two times and remove one pin status - `cid` still going to be pinned.

**Comment by kalambet** [comment] 2021-07-01 12:53
It is going to be fixed in this issue:
https://github.com/ChainSafe/files-api/issues/896

And going to be part of this PR:
https://github.com/ChainSafe/files-api/pull/1209

**Comment by FSM1** [comment] 2021-07-14 15:38
When the above API fix is made and results in an error being return from the API request to create a pin, a Toast or error message in the modal should be displayed to the user explaining why the duplicate CID was not pinned.

**Comment by Tbaut** [comment] 2022-03-17 10:39
Rather than preventing it, we should call a list, and filter by cid, and show a warning below the field in case this cid is already pinned.

**Closed as completed** 2022-03-21 14:47 UTC
Labels: Issue: Bug 🐛, Product: Storage
