### ISSUE TITLE
Files: User cannot select folder in "Copy to Shared Folder" modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1348] opened 2021-07-27 04:13 UTC
**Description**
It is not possible to select a folder in the dropdown field on the "Copy To Shared Folder" modal. 

**To Reproduce**
1. Login to account with access to an existing shared folder
2. Navigate to home and upload a file
3. For the newly created file click the "kebab" menu icon
4. Click the "Copy to shared folder" menu option
5. Attempt to select a shared folder in the modal

**Expected behavior**
It should be possible to select a shared folder in this modal

**Video**

https://user-images.githubusercontent.com/3982665/127094311-deede908-275d-46b0-971c-58f548bc6c7f.mov

**Desktop:**
 - OS: macOS
 - Browser: Firefox /  Chrome
 - Version : 90.0.2 / 91.0.4472.114

**Comment by Tbaut** [comment] 2021-07-27 09:32
Are you able to reproduce all the time? I'm on Firefox and can't reproduce. Is there any error in the console or anything? Anything specific to your setup you can think of?

https://user-images.githubusercontent.com/33178835/127131597-7c8aefaf-f331-4979-a893-b13abc95b5d1.mp4

**Comment by Tbaut** [comment] 2021-07-27 11:15
Maybe @sweetpea22 can try it out on a mac, it should be available on https://files-ui-stage.onrender.com/

**Comment by asnaith** [comment] 2021-07-27 16:00
@Tbaut Hmmm this is odd,  it was 100% reproducible for me yesterday in chrome and firefox but checking again today (same account, same browsers) and it's working normally. Is there any chance intermittent API issues could lead to this weirdness? Can't think of what else it could be.

**Comment by Tbaut** [comment] 2021-08-02 14:27
closing for now since we can't reproduce

**Closed as completed by Tbaut** 2021-08-02 14:27 UTC
Labels: Issue: Bug 🐛, Product: Files
