### ISSUE TITLE
Single file download request has file name repeated in the path

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1499] opened 2021-09-07 17:12 UTC
**Description**
If I intercept download requests for a supported file (https://stage.imploy.site/api/v1/bucket/*/download) I see that the file name is repeated twice in the path which seems odd.

Example: 

```       
        "body": {
            "path": "/logo.png/logo.png"
        }
```

**Expected behavior**
I would expect the path to just be "/logo.png". 

**Notes**
The feature is working as intended even with the file name repeated in the path but I wanted to point this out in case it's unintentional. 

- This happens when downloading supported files from the Preview kebab menu download option
- This doesn't happen when a download request is made for unsupported files
- This doesnt happen for downloads from the File Browser kebab menu

**Comment by FSM1** [comment] 2021-09-08 15:50
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1499?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment] 2021-09-21 08:55
I cannot reproduce this. Neither on FF nor on Brave.
Note that the `download` api call is only fired when we:
- click download from the file browser (before viewing the file)
- double-click on the file or click on the preview menu entry. Downloading from the menu in the preview doesn't fire any other call.

> This happens when downloading supported files from the Preview kebab menu download option

So this to me isn't possible. The files was already downloaded at this point, and there's no more download api call fired when you click on Download.
Also, just to see what would happen, I manually fired a request to the api with a double path, and this result in a "500 internal server error".

Let me know @asnaith if you can pin-point how this happens to you, otherwise we can close.

**Comment by asnaith** [comment] 2021-09-21 15:25
@Tbaut I've just spent 30 mins trying to reproduce it but cannot anymore whereas it was pretty consistent before. I guess we can close this

**Comment by asnaith** [comment] 2021-11-03 20:33
![File Preview -- desktop -- can see unsupported file info and download option (failed)](https://user-images.githubusercontent.com/3982665/140187338-b5fe79a6-ef60-4e90-95bb-8820bc9fb613.png)

I'm seeing instances of this happening again in CI, see the screenshot. 

This doesn't really make sense as it went away for a while and then started happening plus when I test it manually in the browser with the dev tools it looked as expected `{"path":"/file.zip"}`. 

Any ideas?

**Comment by Tbaut** [comment] 2021-11-04 12:55
I was able to reproduce when manually downloading a zip file. Will dig deeper.

**Comment by Tbaut** [comment] 2021-11-04 14:59
I've no clue why this happens. I could reproduce for a short moment.. I could add a couple console.log and then I couldn't reproduce any more :roll_eyes: 

From what I could see, the problem isn't related to `getPathWithFile` , it sounds however related to `currentPath`, which is populated thanks to `extractFileBrowserPathFromURL` that returns the path with the current file already e.g returning `/filename.zip` whereas we expect `/` . When the problem happened the url only contained `/drive`afair, maybe with a trailing slash.

**Comment by FSM1** [comment] 2021-11-08 21:33
> I've no clue why this happens. I could reproduce for a short moment.. I could add a couple console.log and then I couldn't reproduce any more 🙄
> 
> From what I could see, the problem isn't related to `getPathWithFile` , it sounds however related to `currentPath`, which is populated thanks to `extractFileBrowserPathFromURL` that returns the path with the current file already e.g returning `/filename.zip` whereas we expect `/` . When the problem happened the url only contained `/drive`afair, maybe with a trailing slash.

I've spent the better part of a day trying to cause this, testing with multiple different files, as well as search results, and to no avail. I tested with both the naked `url/drive`, `url/drive/` as well as `url/drive/child`, `url/drive/child/` and each time the requests have the correct path. 🤷🏼

**Comment by asnaith** [comment] 2021-11-08 23:20
The last time we noticed this problem it also just went away without any intervention. The automation test is now passing too. Very strange! 😬

**Comment by Tbaut** [comment] 2021-11-09 11:22
It might be some weirdness coming from the api? If the list of files we get is having those double paths?

**Comment by FSM1** [comment] 2021-11-09 13:06
> It might be some weirdness coming from the api? If the list of files we get is having those double paths?

Yeah it is super weird that this happens intermittently... if the `currentPath` were wrong, most of the other calls would also fail, as we depend on that variable for pretty much every single Files API call that uses the file system.

**Comment by Tbaut** [comment] 2021-12-02 11:03
closing this again until it reappears.. hopefully never.

**Closed as completed by Tbaut** 2021-12-02 11:03 UTC
Labels: Issue: Bug 🐛, Product: Files
