### ISSUE TITLE
Invalid share link generates runtime error

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1695] opened 2021-11-02 21:28 UTC
**Describe the bug**
I modified a share link url expecting it to generate a "Token Malformed" error but instead managed to generate a runtime error. Logging this in case it's something we want to handle differently. 

**To Reproduce**

Sign in and then click this link below:

[Modified link that generates error](https://files-ui-stage.onrender.com/link-sharing/read/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibGlua19zaGFyaW5nIiwicGVybWlzc2lvbiI6InJlYWQiLCJpYXQiOjE2MzU4ODc2NjMsImJ1Y2tldF9pZCI6ImM1YWY0OWY0LWQ2MzYtNDEwYS04YTE3LTIzOTM0MGQwYjJmYiIsIm5vbmNlX2lkIjoiNjEzNTdlMDgtYjE0MS00Y2Q1LWE0ZTgtZTQyNmE1MjZlYWEwIn0.3oH7sI5-m_ef6i2vex1jD56LasyxF56Z_74k-vMQQcfMSzS0dvICVOYW1az1HH9Lms8anWC0qqeM8fCDNwhC6g#jQUiOivBajf0K4P7oZjXzE2QSoK%2BJcjPqt%2ByGw6QDak%3D)

Also here is the link that works:

[Legitimate link that should work ](https://files-ui-stage.onrender.com/link-sharing/read/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibGlua19zaGFyaW5nIiwicGVybWlzc2lvbiI6InJlYWQiLCJpYXQiOjE2MzU4ODc2NjMsImJ1Y2tldF9pZCI6ImM1YWY0OWY0LWQ2MzYtNDEwYS04YTE3LTIzOTM0MGQwYjJmYiIsIm5vbmNlX2lkIjoiNjEzNTdlMDgtYjE0MS00Y2Q1LWE0ZTgtZTQyNmE1MjZlYWEwIn0.3oH7sI5-m_ef6i2vex1jD56LasyxF56Z_74k-vMQQcfMSzS0dvICVOYW1az1HH9Lms8anWC0qqeM8fCDNwhC7g#jQUiOivBajf0K4P7oZjXzE2QSoK%2BJcjPqt%2ByGw6QDak%3D)

There's a "#" in the url, to produce this I just changed the sequence before the # from "C7g" to "C6g"

**Expected behavior**
I would expect the app to tell me the token is malformed or the link is unavailable

**Console error**

`{
	"error": {
		"code": 500,
		"message": "runtime error: invalid memory address or nil pointer dereference"
	}
}`

**Screenshots**
<img width="655" alt="Screen Shot 2021-11-02 at 2 06 17 PM" src="https://user-images.githubusercontent.com/3982665/139954157-b6f8c917-90fa-48a7-807d-cfe52b8a45f1.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome (not browser specific) 
 - Version : 95.0.4638.54

**Comment by RyRy79261** [comment] 2021-11-04 06:48
@asnaith so this is an error from the server, basically its the Go equivalent of trying to use an undefined variable 

@kalambet @FSM1 I can either detect the error and make an error on UI side, or we can catch the error on API side and send back a service error to consume

**Comment by ohmpatel1997** [comment] 2021-11-04 07:14
I am already on it. There is a PR for it: [PR](https://github.com/ChainSafe/files-api/pull/1679) 😄

**Comment by asnaith** [comment] 2021-11-04 16:44
Thanks @RyRy79261 I appreciate the explanation of the cause :)

**Comment by FSM1** [comment] 2021-11-10 14:08
> @asnaith so this is an error from the server, basically its the Go equivalent of trying to use an undefined variable
> 
> @kalambet @FSM1 I can either detect the error and make an error on UI side, or we can catch the error on API side and send back a service error to consume

Since this is being handled by the API and the error returned to the UI, I do not think we need separate handling for this case on the UI. Just need to display that the token is invalid, and let the user log in as normal...

**Comment by ohmpatel1997** [comment] 2021-11-10 14:13
The PR is merged, I have checked, its fixed, giving back the internal server error.

**Comment by asnaith** [comment] 2021-11-10 17:05
Hey @FSM1, since Ohm's PR got merged we now see the internal server error message in the UI instead of the runtime error. Do we want to do anything else here on the front end or happy to leave it as is? 

<img width="438" alt="Screen Shot 2021-11-10 at 9 03 57 AM" src="https://user-images.githubusercontent.com/3982665/141159243-036e723d-8975-4602-bb8d-9301c86b5a11.png">

**Comment by FSM1** [comment] 2021-11-10 19:29
> Hey @FSM1, since Ohm's PR got merged we now see the internal server error message in the UI instead of the runtime error. Do we want to do anything else here on the front end or happy to leave it as is?
> 

I would rather display a message about an invalid token. Will also handle the situation where the token body is malformed, and fails to decode.

**Comment by ohmpatel1997** [comment] 2021-11-10 19:40
@FSM1  The issue is, token was actually valid, since @asnaith  only changed the last part of the token (by last part i mean, the signature part of the token). So the token was not malformed, rather the signature was invalid and it failed to verify the signature, and thats the reason server is ending the 500, internal server error. 

If you change the middle part of the token, i.e the payload, the token will become malformed. and it will give back the appropriate error. For ex: please try with this [link](https://files-ui-stage.onrender.com/link-sharing/read/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibGlua1adasdaFyaW5nIiwicGVybWlzc2lvbiI6InJlYWQiLCJpYXQiOjE2MzU4ODc2NjMsImJ1Y2tldF9pZCI6ImM1YWY0OWY0LWQ2MzYtNDEwYS04YTE3LTIzOTM0MGQwYjJmYiIsIm5vbmNlX2lkIjoiNjEzNTdlMDgtYjE0MS00Y2Q1LWE0ZTgtZTQyNmE1MjZlYWEwIn0.3oH7sI5-m_ef6i2vex1jD56LasyxF56Z_74k-vMQQcfMSzS0dvICVOYW1az1HH9Lms8anWC0qqeM8fCDNwhC6g#jQUiOivBajf0K4P7oZjXzE2QSoK%2BJcjPqt%2ByGw6QDak%3D)

Do we want to show custom error message in case of it fails to verify as well or signature is invalid?

**Comment by Tbaut** [comment] 2021-11-10 20:00
I think we do decode the jwt on the front end (we don't check the sig) and already show a nice error if it's malformed.

**Closed as completed** 2021-11-15 14:16 UTC
Labels: Issue: Bug 🐛, Product: Files
